name: Compile Rust-Analyzer for ARMv7 (Raspberry Pi 2+)

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-linux-gnueabihf
        rustup target add armv7-unknown-linux-gnueabihf
    - name: Build
      run: |
        git clone -b release https://github.com/rust-analyzer/rust-analyzer.git
        cd rust-analyzer
        cargo build --release --target=armv7-unknown-linux-gnueabihf
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "rust-analyzer/target/armv7-unknown-linux-gnueabihf/release/rust-analyzer"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: main
        allowUpdates: true
        tag: latest
    - uses: actions/upload-artifact@v2
      with:
        name: rust-analyzer
        path: rust-analyzer/target/armv7-unknown-linux-gnueabihf/release/rust-analyzer
